// aplib_PRETTY_PRINTER

#ifndef DAVE_aplib_PP
#define DAVE_aplib_PP

// INFORMATIVE SECTION
/** This subsystem provides ANSI/VT colourization, and other formatting features, for aplib operations/operands.
Utilizes my repo "ColorConsole", currently located at https://github.com/inventordave2/ColorConsole. That repo will need to be cloned, it's make target invoked ("make colorconsole"), the object file generated by the compiler, and then you would link the output object file "cc.o" to your program object files (aplib, ap_io, [your-program-TU]) at link-time. A sample make target will be avaiable in this repo's Makefile to show a simple way to link this subsystem to your program that presumably also integrates aplib itself.
*/


// STDLIB INC'S
#include <stdio.h>
#include <string.h>


// CUSTOM INC'S
#include "aplib.h"
#include "colour.h" // From https:://github.com/inventordave2/ColorConsole

//ColorConsole object file (see it's repo) needs to be available to link to this file, and presumably a 3rd object file representing
// your user program's entry-point (main function).

/*
DECIMAL/BINARY STRINGS (SIGN SYMBOL +/-)

1 = BRIGHT_BLUE, 0 = BRIGHT_YELLOW (BINARY)
SIGN: + = bright_green, - = bright_red
DEC digits: BRIGHT_WHITE

OPERATORS (AD, SUB, ETC, +, -, *, /, ^) - BRIGHT_CYAN
Program text output FG_BRIGHT_CYAN

Test function output.

NL: words, punctuation
*/

/**
	extern char FG_BLACK[8];
	extern char FG_RED[8];
	extern char FG_GREEN[8];
	extern char FG_YELLOW[8];
	extern char FG_BLUE[8];
	extern char FG_MAGENTA[8];
	extern char FG_CYAN[8];
	extern char FG_WHITE[8];

	extern char FG_BRIGHT_BLACK[8];
	extern char FG_BRIGHT_RED[8];
	extern char FG_BRIGHT_GREEN[8];
	extern char FG_BRIGHT_YELLOW[8];
	extern char FG_BRIGHT_BLUE[8];
	extern char FG_BRIGHT_MAGENTA[8];
	extern char FG_BRIGHT_CYAN[8];
	extern char FG_BRIGHT_WHITE[8];
*/
// DATA STRUCTURES/TYPES


// FNC PROTOTYPES
void setFGColor( int cc );
void setBGColor( int cc );
void setStyle( int sc ); // eg, +i, +b, -i, -b, and so on.
char * truncateAP( AP A );

char * generateSVG( APExp exp );
char * generateLatex_Exp( APExp exp );
char * generateLatex_Number( AP A );

char * formatSign(char sign);
char * formatBinary(char * bin_string);
char * formatAP(AP A);

void normal();
char * c(char * str, char * col);
void print( char * str );

#endif

