// APLIB_PRETTY_PRINTER

#ifndef DAVE_APLIB_PP
#define DAVE_APLIB_PP

// INFORMATIVE SECTION
/** This subsystem provides ANSI/VT colourization, and other formatting features, for APlib operations/operands.
Utilizes my repo "ColorConsole", currently located at https://github.com/inventordave2/ColorConsole. That repo will need to be cloned, it's make target invoked ("make colorconsole"), the object file generated by the compiler, and then you would link the output object file "cc.o" to your program object files (APlib, APlib-output, [your-program-TU]) at link-time. A sample make target will be avaiable in this repo's Makefile to show a simple way to link this subsystem to your program that presumably also integrates APlib itself.
*/


// STDLIB INC'S
#include <stdio.h>
#include <string.h>


// CUSTOM INC'S
#include "APlib.h"
#include "cc/ansivt2.h" // From https:://github.com/inventordave2/ColorConsole

//ColorConsole object file (see it's repo) needs to be available to link to this file, and presumably a 3rd object file representing
// your user program's entry-point (main function).


// DATA STRUCTURES/TYPES


// FNC PROTOTYPES
void print( char * format_string, ... );
void setFGColor( int cc );
void setBGColor( int cc );
void setStyle( int sc ); // eg, +i, +b, -i, -b, and so on.
char * truncateAP( AP a );

char * generateSVG( APExp exp );
char * generateLatex_Exp( APExp exp );
char * generateLatex_Number( AP a );

#endif

